# Reddit Categorization Pipeline Configuration
# Copy this file and customize for your analysis needs

# Subreddit to analyze
subreddit: "fashion"

# Category Configuration
# Option 1: Auto-generate categories (leave predefined_categories empty)
# Option 2: Use predefined categories (list them below)
num_auto_categories: 8
predefined_categories: []
  # Example predefined categories:
  # - "Street Style"
  # - "Formal Wear"
  # - "Thrift Finds"
  # - "Sustainable Fashion"
  # - "Budget Fashion"

# Scraping Parameters
months_back: 6  # How many months of history to scrape
min_score: 50  # Minimum upvote score for posts
min_num_comments: 0  # Minimum comments (0 = no filter)
fetch_all_comments: true  # Whether to fetch full comment trees
max_posts: null  # Maximum posts to scrape (null = unlimited)

# LLM Parameters
openai_model: "gpt-4o-mini"  # Options: gpt-4o-mini, gpt-4o, gpt-4-turbo
temperature: 0.7  # Creativity (0.0-1.0)
max_posts_for_category_gen: 100  # Sample size for category generation
batch_size: 10  # Posts per categorization API call

# Output
output_directory: "pipeline_output"
log_every: 20  # Log progress every N posts

# Example Configurations
# ----------------------

# Example 1: Fashion subreddit with auto-generated categories
# subreddit: "fashion"
# num_auto_categories: 8
# predefined_categories: []

# Example 2: Streetwear with custom categories
# subreddit: "streetwear"
# predefined_categories:
#   - "Outfit Showcase"
#   - "Shopping & Deals"
#   - "Discussion"
#   - "Sneakers & Footwear"
#   - "Brand Talk"

# Example 3: Quick analysis (limited posts)
# subreddit: "malefashionadvice"
# max_posts: 200
# months_back: 3
# num_auto_categories: 6

